---
- name: Full Jetson Setup with uv, MQTT, YOLO and Script Execution
  hosts: jetson
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install core dependencies
      apt:
        name:
          - git
          - python3-pip
          - python3-venv
          - libopencv-dev
          - mosquitto
          - mosquitto-clients
        state: present

    - name: Enable and start mosquitto service
      systemd:
        name: mosquitto
        enabled: yes
        state: started

    - name: Allow anonymous MQTT access (for dev only)
      copy:
        dest: /etc/mosquitto/conf.d/allow-anonymous.conf
        content: |
          listener 1883
          allow_anonymous true
      notify:
        - Restart Mosquitto

    - name: Install uv globally via pip
      pip:
        name: uv
        executable: pip3

    - name: Clone YOLO project
      git:
        repo: 'https://github.com/prakhar105/object-detection.git'
        dest: /home/agxql0015/yolo
        version: main

    - name: Create uv virtual environment
      command: uv venv
      args:
        chdir: /home/agxql0015/yolo
      environment:
        UV_VENV_PATH: /home/agxql0015/yolo/.venv

    - name: Sync dependencies with uv pip sync
      command: uv pip sync requirements.txt
      args:
        chdir: /home/agxql0015/yolo
      environment:
        UV_VENV_PATH: /home/agxql0015/yolo/.venv

    - name: Sync dependencies with uv
      command: uv sync
      args:
        chdir: /home/agxql0015/yolo
      environment:
        UV_VENV_PATH: /home/agxql0015/yolo/.venv

    - name: Run YOLO script (e.g., main.py)
      command: /home/agxql0015/yolo/.venv/bin/python scripts/realtime_video_detect_mqtt.py
      args:
        chdir: /home/agxql0015/yolo

  handlers:
    - name: Restart Mosquitto
      systemd:
        name: mosquitto
        state: restarted
